return {
  s({ trig = (vim.g.mapleader or ";") .. "sg", snippetType = "autosnippet", wordTrig = false},
  t"\\sigma"),
  s({ trig = (vim.g.mapleader or ";") .. "bt", snippetType = "autosnippet", wordTrig = false},
  t"\\beta"),
  s({ trig = (vim.g.mapleader or ";") .. "al", snippetType = "autosnippet", wordTrig = false},
  t"\\alpha"),
  s({ trig = (vim.g.mapleader or ";") .. "dl", snippetType = "autosnippet", wordTrig = false},
  t"\\delta"),
  s({ trig = (vim.g.mapleader or ";") .. "om", snippetType = "autosnippet", wordTrig = false},
  t"\\omega"),
  s({ trig = (vim.g.mapleader or ";") .. "pi", snippetType = "autosnippet", wordTrig = false},
  t"\\pi"),
  s({ trig = (vim.g.mapleader or ";") .. "Sg", snippetType = "autosnippet", wordTrig = false},
  t"\\Sigma"),
  s({ trig = (vim.g.mapleader or ";") .. "Bt", snippetType = "autosnippet", wordTrig = false},
  t"\\Beta"),
  s({ trig = (vim.g.mapleader or ";") .. "Al", snippetType = "autosnippet", wordTrig = false},
  t"\\Alpha"),
  s({ trig = (vim.g.mapleader or ";") .. "Dl", snippetType = "autosnippet", wordTrig = false},
  t"\\Delta"),
  s({ trig = (vim.g.mapleader or ";") .. "Om", snippetType = "autosnippet", wordTrig = false},
  t"\\Omega"),
  s({ trig = (vim.g.mapleader or ";") .. "pi", snippetType = "autosnippet", wordTrig = false},
  t"\\Pi"),
  s({ trig = "\\sigmaM", snippetType = "autosnippet", wordTrig = false},
  t"$\\sigma$"),
  s({ trig = "\\betaM", snippetType = "autosnippet", wordTrig = false},
  t[[$\beta$]]),
  s({ trig = "\\alphaM", snippetType = "autosnippet", wordTrig = false},
  t[[$\alpha$]]),
  s({ trig = "\\deltaM", snippetType = "autosnippet", wordTrig = false},
  t[[$\delta$]]),
  s({ trig = "\\omegaM", snippetType = "autosnippet", wordTrig = false},
  t[[$\omega$]]),
  s({ trig = "\\piM", snippetType = "autosnippet", wordTrig = false},
  t[[$\pi$]]),
  s({ trig = "\\SigmaM", snippetType = "autosnippet", wordTrig = false},
  t[[$\Sigma$]]),
  s({ trig = "\\BetaM", snippetType = "autosnippet", wordTrig = false},
  t[[$\Beta$]]),
  s({ trig = "\\AlphaM", snippetType = "autosnippet", wordTrig = false},
  t[[$\Alpha$]]),
  s({ trig = "\\DeltaM", snippetType = "autosnippet", wordTrig = false},
  t[[$\Delta$]]),
  s({ trig = "\\OmegaM", snippetType = "autosnippet", wordTrig = false},
  t[[$\Omega$]]),
  s({ trig = "\\PiM", snippetType = "autosnippet", wordTrig = false},
  t[[$\Pi$]]),
  s({trig = (vim.g.mapleader or ";") .. "m", snippetType = "autosnippet", wordTrig = false},
  fmta("$<>$", {i(1)})),
  s({trig = (vim.g.mapleader or ";") .. "sup", snippetType = "autosnippet", wordTrig = false},
  fmta("^{<>}", {i(1)})),
  s({trig = (vim.g.mapleader or ";") .. "sub", snippetType = "autosnippet", wordTrig = false},
  fmta("_{<>}", {i(1)})),
  s({trig = (vim.g.mapleader or ";") .. "frac", snippetType = "autosnippet", wordTrig = false},
    fmta([[
    \frac{<>}{<>}
    ]], {
      i(1),
      i(2),
    }
)
),
  s({trig = (vim.g.mapleader or ";") .. "log", snippetType = "autosnippet", wordTrig = false},
  fmta("\\log{<>}", {i(1)})),
  s({trig = (vim.g.mapleader or ";") .. "lnk", snippetType = "autosnippet", wordTrig = false},
  fmta("[<>](<>)", {i(1), i(2)})),
}
