return {
  s({ trig = (vim.g.mapleader or ";") .. "sg", snippetType = "autosnippet"},
  t"\\sigma"),
  s({ trig = (vim.g.mapleader or ";") .. "bt", snippetType = "autosnippet"},
  t"\\beta"),
  s({ trig = (vim.g.mapleader or ";") .. "al", snippetType = "autosnippet"},
  t"\\alpha"),
  s({ trig = (vim.g.mapleader or ";") .. "dl", snippetType = "autosnippet"},
  t"\\delta"),
  s({ trig = (vim.g.mapleader or ";") .. "om", snippetType = "autosnippet"},
  t"\\omega"),
  s({ trig = (vim.g.mapleader or ";") .. "Sg", snippetType = "autosnippet"},
  t"\\Sigma"),
  s({ trig = (vim.g.mapleader or ";") .. "Bt", snippetType = "autosnippet"},
  t"\\Beta"),
  s({ trig = (vim.g.mapleader or ";") .. "Al", snippetType = "autosnippet"},
  t"\\Alpha"),
  s({ trig = (vim.g.mapleader or ";") .. "Dl", snippetType = "autosnippet"},
  t"\\Delta"),
  s({ trig = (vim.g.mapleader or ";") .. "Om", snippetType = "autosnippet"},
  t"\\Omega"),
}
