return {
  s({ trig = (vim.g.mapleader or ";") .. "sg", snippetType = "autosnippet"},
  t"\\sigma"),
  s({ trig = (vim.g.mapleader or ";") .. "bt", snippetType = "autosnippet"},
  t"\\beta"),
  s({ trig = (vim.g.mapleader or ";") .. "al", snippetType = "autosnippet"},
  t"\\alpha"),
  s({ trig = (vim.g.mapleader or ";") .. "dl", snippetType = "autosnippet"},
  t"\\delta"),
  s({ trig = (vim.g.mapleader or ";") .. "om", snippetType = "autosnippet"},
  t"\\omega"),
  s({ trig = (vim.g.mapleader or ";") .. "Sg", snippetType = "autosnippet"},
  t"\\Sigma"),
  s({ trig = (vim.g.mapleader or ";") .. "Bt", snippetType = "autosnippet"},
  t"\\Beta"),
  s({ trig = (vim.g.mapleader or ";") .. "Al", snippetType = "autosnippet"},
  t"\\Alpha"),
  s({ trig = (vim.g.mapleader or ";") .. "Dl", snippetType = "autosnippet"},
  t"\\Delta"),
  s({ trig = (vim.g.mapleader or ";") .. "Om", snippetType = "autosnippet"},
  t"\\Omega"),
  s({ trig = "\\sigmaM", snippetType = "autosnippet"},
  t"$\\sigma$"),
  s({ trig = "\\betaM", snippetType = "autosnippet"},
  t[[$\beta$]]),
  s({ trig = "\\alphaM", snippetType = "autosnippet"},
  t[[$\alpha$]]),
  s({ trig = "\\deltaM", snippetType = "autosnippet"},
  t[[$\delta$]]),
  s({ trig = "\\omegaM", snippetType = "autosnippet"},
  t[[$\omega$]]),
  s({ trig = "\\SigmaM", snippetType = "autosnippet"},
  t[[$\Sigma$]]),
  s({ trig = "\\BetaM", snippetType = "autosnippet"},
  t[[$\Beta$]]),
  s({ trig = "\\AlphaM", snippetType = "autosnippet"},
  t[[$\Alpha$]]),
  s({ trig = "\\DeltaM", snippetType = "autosnippet"},
  t[[$\Delta$]]),
  s({ trig = "\\OmegaM", snippetType = "autosnippet"},
  t[[$\Omega$]]),
  s({trig = (vim.g.mapleader or ";") .. "M", snippetType = "autosnippet"},
  fmta("$<>$", {i(1)})),
  s({trig = (vim.g.mapleader or ";") .. "sup", snippetType = "autosnippet"},
  fmta("^<>", {i(1)})),
  s({trig = (vim.g.mapleader or ";") .. "sub", snippetType = "autosnippet"},
  fmta("_<>", {i(1)})),
  
}
